import * as E from './engine.js';
import * as Art from './art.js';
const unitFacing=new Map();
const $=id=>document.getElementById(id);const NS='http://www.w3.org/2000/svg';
const seedParam=Number(new URLSearchParams(location.search).get('seed'));const initialSeed=Number.isInteger(seedParam)&&seedParam>=1&&seedParam<=999999999?seedParam:4107;
let state=E.createRun(initialSeed),selected='sentinel',mode='move',target=null,hover=null,busy=false,showIntents=false,muted=true,audioCtx=null,runNumber=1,toastTimer=null,lastFocus=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const position=(x,y,h=1)=>({x:450+(x-y)*48,y:211+(x+y)*25-h*22});
function heroArt(type,portrait=false,pose='idle'){const generated=Art.sprite(type,pose);if(generated)return generated;const c=E.CLASSES[type].color;const robes=type==='healer',bow=type==='ranger';return `<ellipse cx="0" cy="3" rx="21" ry="9" fill="#10262b" opacity=".45"/><g class="unit-body"><path d="M-10-7L-10 2L-3 3L0-12M6-12L5 2L14 3L13-10" stroke="#203738" stroke-width="7" stroke-linecap="round"/><path d="M-15-47L-23-14L-4-3L17-12L13-44Z" fill="${robes?'#cfb77f':bow?'#5e9e94':'#c87965'}"/><path d="M-13-43L-13-18L1-9L13-17L10-44Z" fill="${c}"/><path d="M-8-20L9-18M-6-34L10-31" stroke="#476965" stroke-width="3"/><path d="M-12-40L-19-23L-24-25" stroke="${c}" stroke-width="8" stroke-linecap="round"/><path d="M12-39L20-25" stroke="${c}" stroke-width="8" stroke-linecap="round"/><ellipse cx="0" cy="-55" rx="12" ry="14" fill="#dcae8b"/><path d="M-13-51L-12-61L-3-70L9-66L14-55L8-56L5-62L-7-60L-7-49Z" fill="${bow?'#213d3e':robes?'#e7d49d':'#3f5150'}"/><path d="M-1-54L4-54" stroke="#263d3d" stroke-width="2"/><path d="M1-48L5-48" stroke="#a36e5c" stroke-width="1.5"/>${type==='sentinel'?`<path d="M-31-39L-14-43L-6-34L-11-13L-24-7L-33-23Z" fill="#efe0b2" stroke="#476965" stroke-width="2"/><path d="M-22-37L-15-29L-20-17L-27-25Z" fill="#c87965"/><path d="M21-43L24-16" stroke="#dedfc8" stroke-width="4"/><path d="M17-29L29-31" stroke="#e9c68f" stroke-width="3"/>`:bow?`<path d="M-30-32Q-22-47-7-25" stroke="#e1c398" stroke-width="3" fill="none"/><path d="M-30-32L-7-25M-28-22L-9-38" stroke="#d6dac3" stroke-width="1.5"/><path d="M15-49L23-60" stroke="#e1c398" stroke-width="3"/><path d="M18-56L25-51" stroke="#d5e4cf" stroke-width="3"/>`:`<path d="M22-57L22-7" stroke="#bd9974" stroke-width="4"/><path d="M16-64L22-75L29-64L23-56Z" fill="#f2de9d"/><circle cx="22" cy="-64" r="4" fill="#ffefbe"/><path d="M-8-40L5-38L2-26L-10-28Z" fill="#536e64"/>`}</g>`;}
function enemyArt(type,pose='idle'){const generated=Art.sprite(type,pose);if(generated)return generated;if(type==='boss')return `<ellipse cx="0" cy="5" rx="36" ry="17" fill="#13282d" opacity=".6"/><g class="unit-body"><path d="M-28-51L-18-104L11-124L32-81L23-9L2 1L-25-17Z" fill="#354c51" stroke="#668277" stroke-width="2"/><path d="M-18-104L4-72L2 1L-25-17L-28-51Z" fill="#223b43"/><path d="M4-72L11-124L32-81L23-9L2 1Z" fill="#4b6664"/><path d="M-21-64L5-80L25-62L6-42Z" fill="#e79880"/><path d="M-11-62L5-71L15-61L5-53Z" fill="#132c36"/><circle cx="5" cy="-62" r="5" fill="#f3d49b"/><path d="M-18-25L0-37L20-20M-24-87L-9-79M16-104L22-87" stroke="#99ab8e" stroke-width="2"/><ellipse cx="0" cy="-64" rx="43" ry="17" fill="none" stroke="#deb38d" stroke-width="2" transform="rotate(-22 0 -64)"/></g>`;
 const spit=type==='spitter';return `<ellipse cx="0" cy="4" rx="24" ry="10" fill="#10252a" opacity=".5"/><g class="unit-body"><path d="M-11-9L-23 1M-1-7L-6 4M9-10L23 1" stroke="#435c59" stroke-width="6" stroke-linecap="round"/><path d="M-23-29L-13-54L11-59L24-33L12-6L-12-10Z" fill="#385056"/><path d="M-13-54L0-32L-12-10L-23-29Z" fill="#253b43"/><path d="M0-32L11-59L24-33L12-6Z" fill="#536c65"/><path d="M-14-34L0-43L15-31L1-22Z" fill="${spit?'#e9c491':'#da8c75'}"/><ellipse cx="1" cy="-33" rx="5" ry="7" fill="#17313b"/><path d="M-19-44L-28-58L-14-50M16-45L30-59L21-35" fill="#61766a"/>${spit?'<path d="M-26-26L-42-44L-37-12L-17-7M23-23L44-38L36-8L15-10" fill="#b6a889" stroke="#536c65" stroke-width="2"/>':''}</g>`;}
const portrait=type=>Art.portrait(type)||`<svg viewBox="-35 -82 70 90" aria-hidden="true">${heroArt(type,true)}</svg>`;
function background(){return `<defs>
 <linearGradient id="rock-left" x1="0" x2="1"><stop stop-color="#29494b"/><stop offset="1" stop-color="#213d43"/></linearGradient><linearGradient id="rock-right" x1="0" x2="1"><stop stop-color="#254449"/><stop offset="1" stop-color="#335250"/></linearGradient><radialGradient id="eclipse"><stop stop-color="#f1dca5" stop-opacity=".6"/><stop offset=".32" stop-color="#c6c5a0" stop-opacity=".12"/><stop offset="1" stop-color="#7dab9e" stop-opacity="0"/></radialGradient><linearGradient id="mist"><stop stop-color="#83b6a4" stop-opacity="0"/><stop offset=".5" stop-color="#83b6a4" stop-opacity=".12"/><stop offset="1" stop-color="#83b6a4" stop-opacity="0"/></linearGradient><filter id="blur"><feGaussianBlur stdDeviation="12"/></filter><pattern id="paper" width="8" height="8" patternUnits="userSpaceOnUse"><circle cx="2" cy="3" r=".7" fill="#b0d8cc" opacity=".07"/></pattern>
 </defs><rect width="900" height="660" fill="url(#paper)"/>
 <circle class="sun-halo" cx="733" cy="124" r="152" fill="url(#eclipse)"/><circle cx="733" cy="124" r="43" fill="#d4cfa4" opacity=".77"/><circle cx="745" cy="113" r="42" fill="#1d3438"/><circle cx="733" cy="124" r="47" fill="none" stroke="#d4cfa4" stroke-opacity=".16"/><path d="M630 124H680M788 124H830M733 33V70M733 178V204" stroke="#abc4b3" stroke-opacity=".17"/>
 <path d="M0 331L83 208L138 311L204 237L279 352L357 290L435 383L533 292L610 375L708 280L757 356L828 238L900 341V550H0Z" fill="#2c484a" opacity=".34"/><path d="M0 366L100 275L164 367L247 296L321 408L438 353L524 402L599 349L673 423L777 328L861 392L900 362V565H0Z" fill="#325452" opacity=".31"/>
 <path d="M85 204L106 157L121 217L108 233Z" fill="#4b6b62" opacity=".5"/><path d="M835 233L852 183L868 246L852 266Z" fill="#4b6b62" opacity=".4"/>
 <ellipse cx="446" cy="543" rx="333" ry="63" fill="#0a252d" opacity=".35" filter="url(#blur)"/><ellipse cx="424" cy="520" rx="382" ry="28" fill="url(#mist)"/><ellipse cx="426" cy="577" rx="280" ry="19" fill="url(#mist)"/>
 <g opacity=".35" fill="#85a995"><path d="M92 430l9-23 10 20-10 7zM807 404l7-22 9 21-8 5zM761 526l12-28 12 24-12 8z"/></g>
 <g stroke="#90afa0" stroke-opacity=".12" fill="none"><ellipse cx="450" cy="433" rx="368" ry="169"/><path d="M64 433H92M808 433H836M450 249V261M450 603V616"/></g>
 <text x="57" y="452" fill="#90afa0" opacity=".36" font-size="10" font-family="Plex">O</text><text x="835" y="452" fill="#90afa0" opacity=".36" font-size="10" font-family="Plex">L</text>`;}
function decor(t,p){if(Art.ready()){return (t.x*13+t.y*7+state.stage)%7===2&&!E.occupant(state,t.x,t.y)&&!t.fragment?Art.prop('arena-'+state.stage,p.x+13,p.y+1,35):'';}const v=(t.x*13+t.y*7+state.stage)%7;if(v===2&&!E.occupant(state,t.x,t.y)&&!t.fragment)return `<g transform="translate(${p.x+12} ${p.y-4})" pointer-events="none"><path d="M-9 0L-5-13L0-20L6-5L9 0Z" fill="#87a994"/><path d="M0-20L0 0L9 0L6-5Z" fill="#527969"/><path d="M-9 0L-17-5L-10-11L-5-4Z" fill="#789a87"/></g>`;if(v===4)return `<g transform="translate(${p.x-15} ${p.y+2})" pointer-events="none" fill="#a3b197" opacity=".35"><path d="M0 0L-7-5L0-8L6-2ZM6-3L12-6L16-2L11 1Z"/></g>`;return '';}
function renderBoard(){
 const u=state.units.find(u=>u.id===selected);const moves=u?E.reachable(state,u):[];const pulses=E.pulseTiles(state),chosen=target||hover;
 let out=background()+Art.background(state.stage);const sorted=[...state.tiles].sort((a,b)=>(a.x+a.y)-(b.x+b.y)||a.x-b.x);
 for(const t of sorted){const p=position(t.x,t.y,t.h),depth=t.h*22+24;const occupied=E.occupant(state,t.x,t.y);let accessible=mode==='move'&&u?.ap>0&&moves.some(m=>m.x===t.x&&m.y===t.y&&m.cost>0);let aim=(mode==='attack'||mode==='skill')&&u&&occupied&&!E.validate(state,u.id,mode,{id:occupied.id});let picked=chosen&&((chosen.x===t.x&&chosen.y===t.y)||(chosen.id!=null&&chosen.id===occupied?.id));const pulse=pulses.some(v=>v.x===t.x&&v.y===t.y);let fill=t.kind==='moss'?'#68897a':'#789385';if(accessible)fill='#86b1a0';if(aim)fill='#ab8673';if(pulse)fill='#aa9870';if(picked)fill='#c6b48a';
  out+=`<g class="cell ${aim?'cell-target':''} ${picked?'cell-chosen':''}" data-cell="${t.x},${t.y}" data-testid="cell-${t.x}-${t.y}" tabindex="0" role="button" aria-label="Casa ${t.x+1}, ${t.y+1}, altura ${t.h}${occupied?', '+escape(occupied.name):''}${accessible?', movimento disponível':''}${pulse?', fratura perigosa':''}"><path d="M${p.x-48} ${p.y}L${p.x} ${p.y+25}V${p.y+25+depth}L${p.x-48} ${p.y+depth}Z" fill="url(#rock-left)" stroke="#1d3d40" stroke-width="1"/><path d="M${p.x} ${p.y+25}L${p.x+48} ${p.y}V${p.y+depth}L${p.x} ${p.y+25+depth}Z" fill="url(#rock-right)" stroke="#1d3d40" stroke-width="1"/><path d="M${p.x-48} ${p.y+depth}L${p.x} ${p.y+25+depth}L${p.x+48} ${p.y+depth}L${p.x+28} ${p.y+depth+38}L${p.x-8} ${p.y+depth+49}L${p.x-39} ${p.y+depth+24}Z" fill="#223f44" opacity=".9"/><path d="M${p.x-48} ${p.y}L${p.x} ${p.y-25}L${p.x+48} ${p.y}L${p.x} ${p.y+25}Z" class="cell-top" fill="${fill}" stroke="#9cb19a" stroke-opacity=".35" stroke-width="1"/>${Art.tile(t,p,state.stage)}${Art.ready()&&(accessible||aim||pulse||picked)?`<path class="art-cell-highlight" d="M${p.x-48} ${p.y}L${p.x} ${p.y-25}L${p.x+48} ${p.y}L${p.x} ${p.y+25}Z" fill="${fill}" fill-opacity="${picked ? 0.34 : aim ? 0.24 : 0.17}" stroke="${picked?'#f0d597':aim?'#e5927c':'#b0d8cc'}" stroke-width="${picked?2:1}"/>`: ''}<path d="M${p.x-41} ${p.y-1}L${p.x} ${p.y-21}L${p.x+41} ${p.y-1}" fill="none" stroke="#e0d9b2" stroke-opacity=".13"/>
  ${(t.x+t.y)%3===1?`<path d="M${p.x-20} ${p.y+11}L${p.x-19} ${p.y+24}L${p.x-28} ${p.y+29}M${p.x+25} ${p.y+16}L${p.x+24} ${p.y+30}" fill="none" stroke="#789185" opacity=".2"/>`:''}
  ${accessible?`<circle cx="${p.x}" cy="${p.y}" r="3" fill="#dce8cd" opacity=".45"/>`:''}${pulse?`<path d="M${p.x-30} ${p.y}L${p.x-10} ${p.y-8}L${p.x-6} ${p.y+8}L${p.x+20} ${p.y-4}" stroke="#f3d697" stroke-width="2" fill="none"/>`:''}${t.fragment?Art.ready()?Art.prop('fragment',p.x,p.y-5,29):`<g class="fragment" pointer-events="none"><path d="M${p.x} ${p.y-28}L${p.x+7} ${p.y-16}L${p.x} ${p.y-5}L${p.x-7} ${p.y-16}Z" fill="#f0d298" stroke="#ffebaf"/><ellipse cx="${p.x}" cy="${p.y+3}" rx="13" ry="5" fill="#eed598" opacity=".25"/></g>`:''}</g>`;
  out+=decor(t,p);
  const unit=occupied;if(unit){const enemy=unit.side==='enemy',s=Art.hasUnit(unit.type)?1:unit.type==='boss'?1.13:1;const ring=enemy?'#e5927c':'#b0d8cc';out+=`<g class="unit ${unit.id===selected?'unit-selected':''}" data-unit="${unit.id}" data-testid="unit-${unit.id}" tabindex="0" role="button" aria-label="${escape(unit.name)}, ${enemy?'inimigo':'aliado'}, ${unit.hp} de ${unit.maxHp} vida, altura ${t.h}" transform="translate(${p.x} ${p.y-4})"><ellipse class="unit-ring" cx="0" cy="1" rx="27" ry="12" fill="${unit.id===selected?'#efd29813':'none'}" stroke="${ring}"/><g transform="scale(${s})">${enemy?enemyArt(unit.type,unitFacing.get(unit.id)||'idle'):heroArt(unit.type,false,unitFacing.get(unit.id)||'idle')}</g><rect x="-19" y="${Art.hasUnit(unit.type)?-Art.spriteHeight(unit.type)-12:enemy&&unit.type==='boss'?-151:-89}" width="38" height="4" rx="2" fill="#10282c"/><rect x="-19" y="${Art.hasUnit(unit.type)?-Art.spriteHeight(unit.type)-12:enemy&&unit.type==='boss'?-151:-89}" width="${38*unit.hp/unit.maxHp}" height="4" rx="2" fill="${ring}"/>${enemy?`<g transform="translate(-30 ${unit.type==='boss'?-128:-67})"><rect x="-6" y="-7" width="13" height="13" rx="3" fill="#213a3f" stroke="#e5927c" stroke-width=".6"/><text x=".5" y="2" text-anchor="middle" fill="#edb5a0" font-size="8" font-family="Plex">${unit.order}</text></g>`:`<text class="unit-name" x="0" y="22" text-anchor="middle">${escape(unit.name)}</text>${unit.shield?`<text x="27" y="-32" fill="#efd298" font-size="12">+${unit.shield}</text>`:''}`}</g>`;}
 }
 if(mode==='move'&&u?.ap>0&&!busy){for(const m of moves.filter(m=>m.cost>0)){const p=position(m.x,m.y,E.tile(state,m.x,m.y).h);out+=`<path class="move-hit" data-cell="${m.x},${m.y}" d="M${p.x-47} ${p.y}L${p.x} ${p.y-24}L${p.x+47} ${p.y}L${p.x} ${p.y+24}Z" fill="transparent" pointer-events="all" aria-hidden="true"/>`;}}
 if(showIntents){for(const i of E.intents(state)){const e=state.units.find(e=>e.id===i.enemy),a=state.units.find(e=>e.id===i.target),p=position(e.x,e.y,E.height(state,e)),q=position(a.x,a.y,E.height(state,a));out+=`<path class="intent-line" d="M${p.x} ${p.y-28}Q${(p.x+q.x)/2} ${Math.min(p.y,q.y)-95} ${q.x} ${q.y-28}" fill="none" stroke="#e5927c" stroke-width="1.5" opacity=".6"/><circle cx="${q.x}" cy="${q.y-28}" r="4" fill="#e5927c"/>`;}}
 out+='<g id="effects" pointer-events="none"></g>';$('board').innerHTML=out;
}
function render(){const u=state.units.find(u=>u.id===selected);document.body.classList.toggle('is-enemy-phase',busy);$('encounter-name').textContent=E.ENCOUNTERS[state.stage].name;$('encounter-sub').textContent=E.ENCOUNTERS[state.stage].sub;$('stage-label').textContent=(state.stage===3?'Chefe final':'Passagem '+(state.stage+1)+' de 4')+' · Mapa '+state.seed;$('phase-text').textContent=busy?'A sombra age':'Sua equipe';$('round').textContent='Rodada '+state.round;$('relic-summary').textContent=state.relics.length?state.relics.map(r=>r==='edge'?'Cinzel solar: +1 dano':'Manto de maré: +1 bloqueio').join(' · '):'Habilidades gastam 1 luz. Fragmentos no terreno restauram 1.';$('energy-count').textContent=`${state.energy} / ${state.energyMax}`;$('energy-dots').innerHTML=Array.from({length:state.energyMax},(_,i)=>`<i class="energy-dot ${i<state.energy?'full':''}"></i>`).join('');
 $('weather-text').textContent=state.round>=10?'Eclipse total: 5 dano por rodada':E.pulseTiles(state).length?'Fratura ativa: '+(state.stage===3?'3':'2')+' dano':'Eclipse crescente';$('squad').innerHTML=state.units.filter(u=>u.side==='ally').map(a=>`<button class="squad-card ${a.id===selected?'selected':''} ${!E.alive(a)?'dead':''}" data-select="${a.id}" data-testid="select-${a.id}" aria-pressed="${a.id===selected}" ${!E.alive(a)||busy?'disabled':''}><span class="portrait">${portrait(a.type)}</span><span><strong>${a.name}</strong><small>${E.CLASSES[a.type].name}</small><span class="health-track"><i style="width:${100*a.hp/a.maxHp}%"></i></span></span><span class="numbers">${a.hp} / ${a.maxHp}<span class="ap-dots"><b class="${a.ap>0?'full':''}"></b><b class="${a.ap>1?'full':''}"></b></span></span></button>`).join('');
 $('selected-details').innerHTML=u?`<span><strong>${u.name}</strong> · Altura ${E.height(state,u)} · ${u.move} movimento</span><span class="mobile-energy">${u.ap} ações · ${state.energy} luz</span>`:'';
 const actions=[['move','Mover','⌖','1 ação'],['attack','Atacar','✦','1 ação'],['skill',u?.type==='healer'?'Curar':'Habilidade','◈','1 luz'],['guard','Proteger','⬡','Fim da ação']];$('action-bar').innerHTML=actions.map(([id,label,icon,cost])=>`<button class="action-button ${mode===id?'active':''}" data-mode="${id}" id="action-${id}" aria-pressed="${mode===id}" ${busy||!u||!E.alive(u)||u.ap===0||(id==='skill'&&state.energy===0)?'disabled':''}><span class="action-icon" aria-hidden="true">${icon}</span>${label}<small>${cost}</small></button>`).join('');
 $('route-track').innerHTML=['Cais','Jardim','Escadaria','Astrólito'].map((n,i)=>`<div class="route-step ${i===state.stage?'active':''} ${i<state.stage?'done':''}"><b>${i<state.stage?'✓':i+1}</b><span>${n}</span></div>`).join('');
 const plans=E.intents(state);$('intent-list').innerHTML=plans.length?plans.map(i=>{const e=state.units.find(e=>e.id===i.enemy),a=state.units.find(e=>e.id===i.target);return `<button class="intent-row" data-enemy="${e.id}" aria-label="Selecionar ${escape(e.name)}, ordem ${e.order}, ${e.hp} vida" title="${e.hp} / ${e.maxHp} vida. Selecionar alvo."><span><b class="enemy-order">${e.order}</b>${escape(e.name)}</span><strong class="${i.damage?'':'approach'}">${i.damage?`${a.name} −${i.damage}`:`Rumo a ${a.name}`}</strong></button>`;}).join(''):'<p class="intent-explainer">O caminho está livre.</p>';
 $('latest-log').textContent=state.history[0];$('end-turn').disabled=busy||state.phase!=='player';$('toggle-intents').setAttribute('aria-pressed',showIntents);$('toggle-intents').textContent=showIntents?'Ocultar linhas':'Ver no campo';renderPreview();renderBoard();
}
function renderPreview(){const u=state.units.find(u=>u.id===selected);const guardValue=3+(state.relics.includes('ward')?1:0);const info={move:['Mover','Casas claras mostram o alcance. Subir custa +1 por nível. Selecione uma casa para ver o risco.'],attack:['Ataque básico',`${(u?.attack||0)+state.relics.filter(r=>r==='edge').length} dano · Alcance ${u?.range||0}. De uma altura maior: +1 dano e +1 alcance à distância.`],skill:[E.CLASSES[u?.type]?.skill||'Habilidade',E.CLASSES[u?.type]?.desc||''],guard:['Proteger posição',`Bloqueia ${guardValue} dano por ataque até a próxima rodada e atrai inimigos próximos. Consome as ações restantes.`]};let p=target?E.preview(state,selected,mode,target):null;$('confirm').disabled=busy||!p?.ok;$('cancel').disabled=!target||busy;
 if(p?.ok){const unit=state.units.find(a=>a.id===target.id);const name=mode==='move'?`Mover para ${target.x+1}, ${target.y+1}`:mode==='guard'?'Proteger posição':mode==='skill'&&u.type==='healer'?`Curar ${unit.name}`:`${mode==='skill'?E.CLASSES[u.type].skill:'Atacar'}: ${unit.name}`;$('preview-panel').innerHTML=`<h4>${escape(name)}</h4><p>${p.kill?'Golpe fatal. A intenção desse inimigo desaparece.':mode==='move'?`Caminho válido. Subida e terreno incluídos no custo.`:mode==='guard'?'Assuma o risco e proteja a formação.':p.damage<0?'A luz restaura vida nesta expedição.':'Dano garantido. A altura já está incluída.'}</p><div class="preview-stats">${mode==='move'?`<span><strong>${p.cost}</strong>movimento</span><span><strong>${p.height}</strong>altura</span>`:mode==='guard'?`<span><strong>${guardValue}</strong>bloqueio</span>`:`<span><strong>${Math.abs(p.damage)}</strong>${p.damage<0?'cura':'dano'}</span><span><strong>${p.energy||0}</strong>luz</span>`}<span class="${p.risk?'danger':''}"><strong>${p.risk}</strong>risco previsto</span></div>`;}
 else $('preview-panel').innerHTML=`<h4>${info[mode][0]}</h4><p>${p?.error?escape(p.error):busy?'A sombra está resolvendo suas intenções.':u?.ap===0?'Sem ações nesta rodada. Selecione outro aliado ou termine o turno.':info[mode][1]}</p>`;
}
function select(id){if(busy)return;const u=state.units.find(u=>u.id===id);if(!u||!E.alive(u)||u.side!=='ally')return;selected=id;target=null;hover=null;mode='move';sound('select');render();}
function setMode(next){if(busy)return;mode=next;target=next==='guard'?{}:null;hover=null;sound('select');render();}
function chooseCell(x,y){if(busy||state.phase!=='player')return;const occ=E.occupant(state,x,y);if(occ&&occ.side==='ally'&&!(mode==='skill'&&selected==='healer')){select(occ.id);return;}target=mode==='move'?{x,y}:occ?{id:occ.id}:null;if(!target){toast('Escolha uma unidade ao alcance.');return;}const p=E.preview(state,selected,mode,target);if(!p.ok)toast(p.error);sound('select');render();}
function chooseUnit(id){const u=state.units.find(u=>u.id===id);if(u)chooseCell(u.x,u.y);}
async function confirmAction(){if(busy||!target)return;const origin=state.units.find(u=>u.id===selected);const from=position(origin.x,origin.y,E.height(state,origin));const result=E.act(state,selected,mode,target);if(!result.ok){toast(result.error);return;}const events=result.events;const actedMode=mode;updateFacing(events);target=null;hover=null;if(origin.ap===0){const next=E.team(state).find(u=>u.ap>0);if(next)selected=next.id;}mode='move';render();animate(events,from);if(actedMode==='attack'||actedMode==='skill'){const node=document.querySelector(`[data-unit="${origin.id}"]`);Art.setPose(node,origin.type,actedMode==='skill'?'skill':'attack');setTimeout(()=>Art.setPose(node,origin.type,unitFacing.get(origin.id)||'idle'),520);}sound(events.some(e=>e.type==='heal')?'heal':events.some(e=>e.type==='hit')?'hit':'move');if(state.phase==='reward'||state.phase==='victory'){busy=true;$('end-turn').disabled=true;await delay(650);busy=false;showOutcome();}}
async function endTurn(){if(busy||state.phase!=='player')return;target=null;hover=null;busy=true;sound('end');render();await delay(350);const attacks=E.intents(state).filter(i=>{const e=state.units.find(u=>u.id===i.enemy),a=state.units.find(u=>u.id===i.target);return e&&a&&E.canAttack(state,{...e,x:i.x,y:i.y},a);}).map(i=>i.enemy);const events=E.enemyTurn(state);updateFacing(events);render();let hitIndex=0;for(const event of events){if(event.type==='hit'&&hitIndex<attacks.length){const attackerId=attacks[hitIndex++],attacker=state.units.find(u=>u.id===attackerId);const node=document.querySelector(`[data-unit="${attacker.id}"]`);Art.setPose(node,attacker.type,'attack');setTimeout(()=>Art.setPose(node,attacker.type,'idle'),420);}animate([event]);if(event.type==='hit')sound('enemy');await delay(event.type==='hit'?140:70);}await delay(500);busy=false;selected=E.team(state).find(u=>u.ap>0)?.id||E.team(state)[0]?.id||'sentinel';mode='move';render();if(state.phase!=='player')showOutcome();}
function delay(ms){return new Promise(r=>setTimeout(r,ms));}
function updateFacing(events){for(const e of events){if(e.type!=='move'||!e.from)continue;const u=state.units.find(u=>u.id===e.id);if(!u)continue;const dx=(u.x-e.from.x)-(u.y-e.from.y),dy=(u.x-e.from.x)+(u.y-e.from.y);unitFacing.set(u.id,dy<0?'idle_ne':dx<0?'idle_sw':'idle');}}
function animate(events,from){const layer=$('effects');if(!layer)return;for(const e of events){const u=state.units.find(u=>u.id===e.id);if(!u)continue;const p=position(u.x,u.y,E.height(state,u));const node=document.querySelector(`[data-unit="${u.id}"]`);if(e.type==='move'||e.type==='push'){node?.classList.add('moving');setTimeout(()=>node?.classList.remove('moving'),450);}if(e.type==='hit'||e.type==='heal'){node?.classList.add(e.type);if(e.type==='hit')Art.setPose(node,u.type,'hurt');setTimeout(()=>{node?.classList.remove(e.type);Art.setPose(node,u.type,unitFacing.get(u.id)||'idle');},500);const g=document.createElementNS(NS,'g');g.setAttribute('transform',`translate(${p.x} ${p.y-80})`);g.innerHTML=`<text class="damage-number" text-anchor="middle" fill="${e.type==='heal'?'#b0d8cc':'#f0c4a1'}">${e.type==='heal'?'+':'−'}${e.n}</text>`;layer.append(g);const circle=document.createElementNS(NS,'circle');circle.setAttribute('cx',p.x);circle.setAttribute('cy',p.y-30);circle.setAttribute('r',12);circle.setAttribute('stroke',e.type==='heal'?'#b0d8cc':'#e5927c');circle.setAttribute('stroke-width',2);circle.setAttribute('fill','none');circle.setAttribute('class','impact-halo');layer.append(circle);if(from){const beam=document.createElementNS(NS,'path');beam.setAttribute('d',`M${from.x} ${from.y-35}L${p.x} ${p.y-35}`);beam.setAttribute('stroke',e.type==='heal'?'#b0d8cc':'#efd298');beam.setAttribute('class','effect-beam');layer.append(beam);}setTimeout(()=>{g.remove();circle.remove();},1000);}}}
function sound(kind){if(muted)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const now=audioCtx.currentTime;const freqs={select:[330],move:[220,294],hit:[110,82],enemy:[90,66],heal:[392,494,587],end:[196,147],victory:[294,392,494,587],defeat:[147,110,73]};for(const [i,f] of (freqs[kind]||[330]).entries()){const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=kind==='hit'||kind==='enemy'?'triangle':'sine';osc.frequency.setValueAtTime(f,now+i*.075);gain.gain.setValueAtTime(.0001,now+i*.075);gain.gain.exponentialRampToValueAtTime(.06,now+i*.075+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+i*.075+.28);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(now+i*.075);osc.stop(now+i*.075+.3);}}catch{toast('Áudio indisponível neste navegador. O jogo continua.');muted=true;}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function openDialog(html,focusId=null){lastFocus=document.activeElement;$('overlay').innerHTML=html;$('overlay').hidden=false;setTimeout(()=>$(focusId)?.focus()||$('overlay').querySelector('button')?.focus(),0);}
function closeDialog(){if(['reward','victory','defeat'].includes(state.phase))return;$('overlay').hidden=true;lastFocus?.focus();}
function showOutcome(){if(state.phase==='reward'){sound('heal');openDialog(`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="reward-title"><p class="dialog-top">Passagem ${state.stage+1} concluída</p><h2 id="reward-title">O mapa continua.</h2><p>Vida e luz seguem com a equipe. Escolha uma descoberta e a rota para ${E.ENCOUNTERS[state.stage+1].name.toLowerCase()}.</p><div class="reward-options">${E.REWARDS.map(r=>`<button class="reward-card" data-reward="${r.id}" data-testid="reward-${r.id}"><span class="reward-art" aria-hidden="true">${Art.reward(r.id)||(r.id==='calm'?'☼':r.id==='edge'?'⟡':'⬡')}</span><strong>${r.name}</strong><small>${r.route}</small><p>${r.id==='ward'&&state.relics.includes('ward')?'Manto já coletado. +1 luz. Recupera 3 vida.':r.desc}</p><b>${r.effect}</b></button>`).join('')}</div><p style="font-size:10px;margin-top:16px">Aliados caídos se recuperam com uma rota de cura. Cada passagem restaura mais 2 luz.</p></section>`);}
 else if(state.phase==='victory'||state.phase==='defeat'){const won=state.phase==='victory';sound(won?'victory':'defeat');openDialog(`<section class="dialog result-dialog" role="dialog" aria-modal="true" aria-labelledby="result-title"><svg class="result-art" viewBox="0 0 130 130" aria-hidden="true"><circle cx="65" cy="65" r="48" fill="none" stroke="#6d8d7e"/><circle cx="65" cy="65" r="36" fill="${won?'#efd298':'#476966'}"/>${won?'<path d="M65 16V35M65 95V114M16 65H35M95 65H114M30 30L42 42M88 88L100 100M30 100L42 88M88 42L100 30" stroke="#efd298" stroke-width="2"/><path d="M41 66L57 81L88 48" fill="none" stroke="#254243" stroke-width="5"/>':'<circle cx="78" cy="56" r="35" fill="#243c3d"/><path d="M39 93L49 80L57 94L68 84L77 96" stroke="#e5927c" fill="none" stroke-width="2"/>'}</svg><p class="dialog-top">${won?'Expedição concluída':'Expedição perdida'}</p><h2 id="result-title">${won?'O horizonte voltou.':'A luz se apagou.'}</h2><p>${won?'Iara, Noa e Sol deixaram um mapa onde antes só havia sombra. O arquipélago tem um novo amanhecer.':'O eclipse alcançou sua equipe. A próxima expedição começa com um novo mapa: use altura, proteção e luz para mudar o destino.'}</p><div class="result-stats"><span><strong>${state.stage+1}/4</strong>passagens</span><span><strong>${state.kills}</strong>sombras vencidas</span><span><strong>${state.totalTurns}</strong>turnos inimigos</span></div><button class="primary-button" id="new-run-result" data-new-run>Nova expedição</button></section>`,'new-run-result');}}
function help(){openDialog(`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="guide-title"><button class="close" data-close aria-label="Fechar guia">×</button><p class="dialog-top">Guia da expedição</p><h2 id="guide-title">Leia a pedra. Proteja a luz.</h2><p>Três cartógrafos, três passagens e um chefe. A expedição começa agora; cada decisão deixa marcas no caminho.</p><div class="help-grid"><div><h3>1. Prepare, depois confirme</h3><p>Selecione Iara, Noa ou Sol. Escolha uma ação e toque em uma casa ou unidade. A prévia informa o dano e o risco antes de confirmar.</p></div><div><h3>2. A altura muda a luta</h3><p>Subir custa movimento extra. Atacar de cima causa +1 dano. Ataques à distância ganham +1 alcance. Cada cartógrafo tem 2 ações por rodada.</p></div><div><h3>3. Três funções, uma equipe</h3><p>Iara suporta a linha e empurra inimigos. Noa alcança a sombra de longe. Sol cura com luz ou ataca com o seu bastão.</p></div><div><h3>4. Siga as intenções</h3><p>O inimigo busca alvos vulneráveis; proteger atrai a sombra e bloqueia dano. As intenções se atualizam após cada ação. Fraturas atingem a linha marcada no fim do turno.</p></div><div><h3>5. Economize a luz</h3><p>Habilidades consomem 1 luz compartilhada. Fragmentos dourados restauram 1. Vida, relíquias e luz persistem entre as passagens.</p></div><div><h3>6. Não espere o eclipse</h3><p>Após 10 rodadas, cada aliado sofre 5 dano por rodada. Vença todos os inimigos para escolher uma rota. Uma rota de cura recupera aliados caídos.</p></div></div><p style="font-size:11px;margin-bottom:16px">Código do mapa: ${state.seed}. Nova expedição muda o relevo, fragmentos e a sombra. O mesmo código reproduz a run em <code>?seed=${state.seed}</code>.</p><div class="help-keys"><kbd>1</kbd><kbd>2</kbd><kbd>3</kbd>aliados &nbsp; <kbd>M</kbd>mover <kbd>A</kbd>atacar <kbd>H</kbd>habilidade <kbd>G</kbd>proteger <kbd>Enter</kbd>confirmar <kbd>Esc</kbd>cancelar <kbd>Espaço</kbd>turno. Casas aceitam foco e setas.</div><button class="primary-button" data-close>Voltar à expedição</button></section>`);}
function restartPrompt(){if(busy)return;openDialog(`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="restart-title"><button class="close" data-close aria-label="Fechar">×</button><p class="dialog-top">Novo mapa</p><h2 id="restart-title">Começar outra expedição?</h2><p>A expedição atual termina. A nova equipe começa no cais com vida e luz completas.</p><div class="restart-actions"><button class="primary-button" data-new-run>Nova expedição</button><button class="text-button" data-close>Continuar esta</button></div></section>`);}
function newRun(){unitFacing.clear();runNumber++;state=E.createRun((initialSeed+runNumber*313)%999999999||4107);selected='sentinel';mode='move';target=null;hover=null;busy=false;showIntents=false;$('overlay').hidden=true;render();toast('Nova expedição. O mapa mudou; a luz está completa.');$('action-move').focus();}
$('board').addEventListener('click',event=>{const unit=event.target.closest('[data-unit]');if(unit){chooseUnit(unit.dataset.unit);return;}const cell=event.target.closest('[data-cell]');if(cell){const [x,y]=cell.dataset.cell.split(',').map(Number);chooseCell(x,y);}});
$('board').addEventListener('keydown',event=>{const element=event.target.closest('[data-cell],[data-unit]');if(!element)return;if(event.key==='Enter'){event.preventDefault();event.stopPropagation();element.click();}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();event.stopPropagation();const unit=element.dataset.unit?state.units.find(u=>u.id===element.dataset.unit):null;const [x,y]=unit?[unit.x,unit.y]:element.dataset.cell.split(',').map(Number);const delta={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[event.key];document.querySelector(`[data-cell="${x+delta[0]},${y+delta[1]}"]`)?.focus();}});
$('intent-list').addEventListener('click',event=>{const b=event.target.closest('[data-enemy]');if(!b||busy||state.phase!=='player')return;if(mode==='move'||mode==='guard'||(mode==='skill'&&selected==='healer'))mode='attack';target={id:b.dataset.enemy};const p=E.preview(state,selected,mode,target);if(!p.ok)toast(p.error);render();});
$('squad').addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b)select(b.dataset.select);});$('action-bar').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b&&!b.disabled)setMode(b.dataset.mode);});$('confirm').onclick=confirmAction;$('end-turn').onclick=endTurn;$('cancel').onclick=()=>{target=null;hover=null;render();};$('toggle-intents').onclick=()=>{showIntents=!showIntents;render();};$('sound').onclick=()=>{muted=!muted;$('sound').innerHTML=`♪ <span>Áudio ${muted?'off':'on'}</span>`;$('sound').setAttribute('aria-label',muted?'Ativar áudio':'Silenciar áudio');sound('heal');};$('help').onclick=help;$('restart').onclick=restartPrompt;$('log-toggle').onclick=()=>openDialog(`<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="log-title"><button class="close" data-close aria-label="Fechar diário">×</button><h2 id="log-title">Diário de campo</h2><ol class="log-list">${[...state.history].reverse().map(l=>`<li>${escape(l)}</li>`).join('')}</ol><button class="primary-button" data-close>Voltar à expedição</button></section>`);
$('overlay').addEventListener('click',event=>{const reward=event.target.closest('[data-reward]');if(reward){E.chooseReward(state,reward.dataset.reward);selected=E.team(state)[0]?.id||'sentinel';mode='move';target=null;$('overlay').hidden=true;render();sound('heal');$('action-move').focus();}if(event.target.closest('[data-close]'))closeDialog();if(event.target.closest('[data-new-run]'))newRun();});
document.addEventListener('keydown',e=>{if(!$('overlay').hidden){if(e.key==='Escape')closeDialog();if(e.key==='Tab'){const buttons=[...$('overlay').querySelectorAll('button')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}return;}if(e.target.closest('input,textarea')||busy||e.ctrlKey||e.metaKey||e.altKey)return;if(['1','2','3'].includes(e.key)){select(Object.keys(E.CLASSES)[Number(e.key)-1]);e.preventDefault();}const action={m:'move',a:'attack',h:'skill',g:'guard'}[e.key.toLowerCase()];if(action){const u=state.units.find(u=>u.id===selected);if(u?.ap>0&&(action!=='skill'||state.energy>0))setMode(action);e.preventDefault();}if(e.key==='Enter'&&!e.target.closest('button,[data-cell],[data-unit]')){e.preventDefault();confirmAction();}if(e.key==='Escape'){target=null;render();}if(e.code==='Space'&&!e.target.closest('button')){e.preventDefault();endTurn();}});
window.__game={snapshot:()=>E.snapshot(state),ui:()=>({selected,mode,target,busy,runNumber}),art:()=>Art.info(),version:'1.1.0'};
render();
Art.load().then(loaded=>{if(loaded)render();}).catch(error=>{console.warn('Arte não carregada; camada vetorial recuperável.',error.message);});
