import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {trails,resolveTrail} from '../src/trails.mjs';
const root=new URL('../',import.meta.url);
const cssFiles=['assets/design-system/tokens/bancada.css','assets/design-system/bancada.css','src/styles.css'];
const css=(await Promise.all(cssFiles.map(f=>readFile(new URL(f,root),'utf8')))).join('\n').replaceAll('url("assets/marca/vk.svg")','url("../assets/design-system/assets/marca/vk.svg")');
await writeFile(new URL('src/site.generated.css',root),'/* Generated by npm run build. Edit src/styles.css or source tokens. */\n'+css);
// Preserve paid source PNGs. Verify controller receipts, then encode delivery WebP without crop/resize.
const receipt=JSON.parse(await readFile(new URL('asset-manifest.json',root),'utf8'));
const optimized=[];
for(const id of ['home-investigacao-panorama','home-investigacao-mobile']){
 const input=new URL(`assets/revisao-1/${id}.png`,root),output=new URL(`assets/revisao-1/${id}.webp`,root);
 const buffer=await readFile(input),sha256=createHash('sha256').update(buffer).digest('hex');
 const asset=receipt.assets.find(x=>x.id===id);
 if(!asset||asset.model_id!=='gpt-image-2.5-sunburst'||asset.sha256!==sha256)throw Error(`Manifesto/asset divergente: ${id}`);
 const meta=await sharp(buffer).metadata();
 if(meta.width!==asset.actual_width||meta.height!==asset.actual_height)throw Error(`Dimensões divergentes: ${id}`);
 const result=await sharp(buffer).webp({quality:88,effort:6}).toFile(fileURLToPath(output));
 const responsive=[];
 for(const width of id.endsWith('mobile')?[384,768,1280]:[768,1280]){
  const path=`assets/revisao-1/${id}-${width}.webp`;
  const info=await sharp(buffer).resize({width,withoutEnlargement:true}).webp({quality:86,effort:6}).toFile(fileURLToPath(new URL(path,root)));
  responsive.push({path,width:info.width,height:info.height,bytes:info.size});
 }
 optimized.push({id,model_id:asset.model_id,generation_id:asset.generation_id,result_id:asset.result_id,source_sha256:sha256,source_bytes:buffer.length,width:result.width,height:result.height,webp_bytes:result.size,responsive,conversion:'Full WebP: quality 88 effort 6, no crop or resize. Responsive derivatives: width-only resize, quality 86, no crop. Source PNG preserved.'});
}
await writeFile(new URL('assets-verificados.json',root),JSON.stringify({verified_at:new Date().toISOString(),assets:optimized},null,2)+'\n');
const catalog=JSON.parse(await readFile(new URL('data/catalog.json',root),'utf8'));
// Delivery thumbnails retain the whole 16:9 official image; portrait remains its own photographic layer.
const renderedIds=[...new Set([...trails.map(t=>t.videoId),'YyD1F1O-nAY','Y25lryXxqlY','RZNmluFIgK0'])];
for(const id of renderedIds){
 const buffer=await readFile(new URL(`assets/revisao-1/videos/${id}.jpg`,root));
 const meta=await sharp(buffer).metadata();if(meta.width!==1280||meta.height!==720)throw Error(`Thumbnail 16:9 inválida: ${id}`);
 await sharp(buffer).webp({quality:88,effort:5}).toFile(fileURLToPath(new URL(`assets/revisao-1/videos/${id}.webp`,root)));
 await sharp(buffer).resize({width:640}).webp({quality:88,effort:5}).toFile(fileURLToPath(new URL(`assets/revisao-1/videos/${id}-640.webp`,root)));
}
await sharp(fileURLToPath(new URL('assets/retratos/vk-recorte-1400.webp',root))).resize({width:700}).webp({quality:90,effort:6}).toFile(fileURLToPath(new URL('assets/revisao-1/vk-retrato-700.webp',root)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeName={video:'Vídeo',tutorial:'Tutorial',project:'Projeto'};
const date=d=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(d));
const renderVideo=async(item,kind='featured')=>{
 const base=`assets/revisao-1/videos/${item.id}`;
 const sizes=kind==='trail'?'(max-width:640px) calc(100vw - 76px), (max-width:800px) calc(100vw - 116px), (max-width:1100px) 42vw, 580px':'(max-width:640px) calc(100vw - 36px), (max-width:800px) 46vw, 30vw';
 return `<div class="media-frame video-frame"><img src="${base}.webp" srcset="${base}-640.webp 640w, ${base}.webp 1280w" sizes="${sizes}" width="1280" height="720" alt="Thumbnail original: ${esc(item.title)}" loading="lazy"><span class="play-label" aria-hidden="true">Assistir ↗</span></div>`;
};
const resolved=trails.map(t=>resolveTrail(t,catalog));
const trailHTML=(await Promise.all(resolved.map(async t=>`<article class="trail-panel" data-trail-panel="${t.id}" aria-labelledby="trail-${t.id}-title"><a class="trail-video-link media-card" href="${esc(t.video.url)}">${await renderVideo(t.video,'trail')}<span class="trail-video-title">${esc(t.video.title)} <span aria-hidden="true">↗</span></span><span class="trail-video-date">Vídeo de <time datetime="${esc(t.video.date)}">${date(t.video.date)}</time></span></a><div class="trail-copy"><p class="trail-caption">Seu ponto de partida em ${esc(t.label)}</p><h2 id="trail-${t.id}-title">${esc(t.question)}</h2><p>${esc(t.premise)}</p><a class="trail-next" href="${esc(t.next.url)}">${esc(t.nextLabel)} <span aria-hidden="true">↗</span></a><div class="trail-actions"><a class="button button-primary" data-explore-theme="${esc(t.theme)}" href="#acervo">${esc(t.action)} <span aria-hidden="true">↓</span></a><a class="text-link" href="${esc(t.video.url)}">Assistir ao vídeo <span aria-hidden="true">↗</span></a></div></div></article>`))).join('\n');
const selections=[
 {id:'YyD1F1O-nAY',question:'IA local. E o uso real?',tag:'IA local',deck:'Bonsai 2 no M4 Max: tarefas, espera e etapas que precisam terminar.'},
 {id:'Y25lryXxqlY',question:'O teste vale o que custa?',tag:'IA na prática',deck:'Um teste do Opus 5.5, com o custo e a espera no próprio título.'},
 {id:'RZNmluFIgK0',question:'Um agente consegue jogar Doom?',tag:'Games e IA',deck:'O Jev entra em Doom sem enxergar a tela. Uma investigação entre dois mundos do canal.'}
];
const featured=(await Promise.all(selections.map(async(s,i)=>{
 const item=catalog.find(x=>x.id===s.id);if(!item)throw Error(`Missing ${s.id}`);
 return `<a class="featured-card featured-${i} media-card" href="${esc(item.url)}">${await renderVideo(item)}<div class="featured-copy"><div class="feature-meta"><span>${esc(s.tag)}</span><time datetime="${esc(item.date)}">${date(item.date)}</time></div><h3>${esc(s.question)}</h3><p>${esc(s.deck)}</p><span class="episode-title">${esc(item.title)} <span aria-hidden="true">↗</span></span></div></a>`;
}))).join('\n');
// Dated items first. Undated entries retain grouping; never infer dates.
const ordered=[...catalog.filter(x=>x.date).sort((a,b)=>b.date.localeCompare(a.date)),...catalog.filter(x=>!x.date&&x.type==='tutorial'),...catalog.filter(x=>!x.date&&x.type==='project'),...catalog.filter(x=>!x.date&&x.type==='video')];
const archive=ordered.map(x=>`<a class="archive-item" href="${esc(x.url)}" data-title="${esc(x.title)}" data-description="${esc(x.description)}" data-theme="${esc(x.theme)}" data-type="${x.type}"><div class="archive-item-meta"><span>${typeName[x.type]}<span class="meta-divider">/</span>${esc(x.theme)}</span>${x.date?`<time datetime="${esc(x.date)}">${date(x.date)}</time>`:''}</div><h3>${esc(x.title)}</h3><span class="archive-destination">${x.type==='video'?'Assistir no YouTube':x.url.includes('github.com')?'Abrir repositório':'Explorar'} <span aria-hidden="true">↗</span></span></a>`).join('\n');
const template=await readFile(new URL('src/index.template.html',root),'utf8');
const html=template.replace('{{TRAILS}}',trailHTML).replace('{{FEATURED}}',featured).replace('{{ARCHIVE}}',archive).replaceAll('{{COUNT}}',catalog.length);
if(/\{\{[A-Z]+\}\}/.test(html))throw Error('Unresolved template placeholder');
await writeFile(new URL('index.html',root),html);
// Self-contained relative build, usable under any local gallery prefix. Only this piece's dist is replaced.
const dist=new URL('dist/',root);await rm(dist,{recursive:true,force:true});await mkdir(new URL('src/',dist),{recursive:true});
await writeFile(new URL('index.html',dist),html);
await cp(new URL('assets/',root),new URL('assets/',dist),{recursive:true});
for(const file of ['site.generated.css','app.mjs','search.mjs'])await cp(new URL(`src/${file}`,root),new URL(`src/${file}`,dist));
console.log(`Built index.html and dist/: ${catalog.length} real entries, ${resolved.length} interactive trails, ${selections.length} further videos. Relative paths.`);
